name: PR Closed Cleanup

on:
  issues:
    types: [opened]
    
jobs:
  show-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: "${{ toJSON(github) }}"
        run: echo "$GITHUB_CONTEXT"
